id: eda50ce3b3534dc488d996a2c164a0d4
initial_creation_type: ocr
source_metadata:
  volumes:
    eef9823cb4a94526a137b40386cb263c:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
