id: D0CB8C865
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:11:51+00:00'
last_modified: '2022-05-26T12:34:35.566308+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    ff5b:
      image_group_id: I1PD95883
      title: དགེ་བའི་འདོད་འཇོ།
      total_pages: 1044
      order: 38
      base_file: ff5b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
